### ISSUE TITLE
2018 Schematron : VOC.xml file does not contain CMS Program Names

### ISSUE THREAD

**Issue by jayeshkotak** [esacinc/qrda#1]
Rule is looking for Program Names in VOC.xml file.
<sch:assert 
id="a-CMS_0026-error" 
test="@extension=document('voc.xml')/voc:systems/voc:system[@valueSetOid='2.16.840.1.113883.3.249.14.103']/voc:code/@value">
This id SHALL contain exactly one [1..1] @extension, 
which SHALL be selected from ValueSet QRDA-I CMS Program Name urn:oid:2.16.840.1.113883.3.249.14.103 STATIC 2016-03-01 (CONF:CMS_0026).
</sch:assert>

2017 VOC.xml file contains required information for HQR and PQRS..
<system valueSetOid="2.16.840.1.113883.3.249.14.103" valueSetName="QRDA-I CMS Program Name ">
<code value="PQRS_MU_INDIVIDUAL" displayName="PQRS Meaningful Use Individual" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="PQRS_MU_GROUP" displayName="PQRS Meaningful Use Group" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="CEC" displayName="Comprehensive End-Stage Renal Disease CARE Initiative" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="HQR_EHR" displayName="Hospital Quality Reporting for the EHR Incentive Program" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="HQR_IQR" displayName="Hospital Quality Reporting for the Inpatient Quality Reporting Program" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="HQR_EHR_IQR" displayName="Hospital Quality Reporting for the EHR Incentive Program and the IQR Program" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
<code value="CDAC_HQR_EHR" displayName="CDAC_HQR_EHR" codeSystemName="CMS Program" codeSystem="2.16.840.1.113883.3.249.7" />
</system>

**Comment by jayeshkotak** [comment]
Please notify Estelle Noone also.

Estelle.Noone@decc.hcqis.org

**Comment by mholck** [comment]
At the time of publishing we were still waiting for the official list of program names. I believe we have the list now so with the next update the program names will be updated. For HQR the program names will be

HQR_IQR_VOL – Hospital Quality Reporting for Inpatient Quality Reporting Program voluntary submissions
HQR_EPM_VOL – Hospital Quality Reporting for Episode Payment Model voluntary submissions

**Comment by mholck** [comment]
Created ESAC JIRA Ticket QRDATEST-2 for this issue
