### ISSUE TITLE
Condition for the rule CMS_0051 and CMS_0039 is not properly written.

### ISSUE THREAD

**Issue by jayeshkotak** [esacinc/qrda#3]
Condition for the rule CMS_0051 and CMS_0039 is not properly written. I believe it will reject almost all the files.

Need to replace "cda:observation" with "child::node()".

Note :: 2018 Schematron Rule
<sch:assert 
id="a-CMS_0051-error" 
test="count(cda:entry[cda:observation[cda:templateId[@root != '2.16.840.1.113883.10.20.24.3.55']]]) &gt; 0">
SHALL contain at least one [1..*] entry (CONF:CMS_0051) such that
it SHALL contain exactly one [1..1] entry template that is other than the 
Patient Characteristic Payer (identifier: urn:oid:2.16.840.1.113883.10.20.24.3.55) (CONF:CMS_0039).
</sch:assert>

Note :: 2017 Schematron Rule
<sch:assert 
id="a-CMS_0051-error" 
test="count(cda:entry[count(child::node()[cda:templateId[@root!='2.16.840.1.113883.10.20.24.3.55']])=1]) &gt; 0">
SHALL contain at least one [1..*] entry (CONF:CMS_0051) such that it
SHALL contain exactly one [1..1] entry template that is other than 
the Patient Characteristic Payer (identifier: urn:oid:2.16.840.1.113883.10.20.24.3.55) (CONF:CMS_0039).
</sch:assert>

**Comment by jayeshkotak** [comment]
Please notify Estelle Noone also.
Estelle.Noone@decc.hcqis.org

**Comment by mholck** [comment]
This issue was already reported in the ESAC JIRA as issue QRDATEST-1 and has been corrected. When we publish a new 2018 HQR Schematron this fix will be included.

**Comment by mholck** [comment]
Closed as duplicate
